[env]
TERM = "xterm-256color"

[colors.bright]
black = "#5B62A0"
blue = "#00AAFF"
cyan = "#00FFFF"
green = "#AAFF00"
magenta = "#FF00FF"
red = "#FF1744"
white = "#E0E6FF"
yellow = "#FF9100"

[colors.normal]
black = "#343760"
blue = "#2979FF"
cyan = "#00E5FF"
green = "#76FF03"
magenta = "#D500F9"
red = "#FF1744"
white = "#A4ADDB"
yellow = "#FFD600"

[colors.primary]
background = "#000000"
foreground = "#C8D8FF"


[font]
size =13 
[font.normal]
# family = "JetBrains Mono Nerd Font"
style = "Bold"

# [font.bold]
# family = "JetBrains Mono Nerd Font"
# style = "Bold"




[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "R"
mods = "Control|Shift"




[window]
blur = true
decorations = "none"
opacity = 0.8
startup_mode = "Maximized"

[window.dimensions]
columns = 170
lines = 40

[window.padding]
x = 5
y = 5
